### ISSUE TITLE
Личный кабинет

### ISSUE THREAD

**Issue by vehsamrak** [vehsamrak/BarchartTasks#5]
Создание личного кабинета с отображением данных:
- имя пользователя
- дата регистрации
- количество стратегий, из них Х открытых
- список открытых стратегий

**Comment by vehsamrak** [comment]
- количество стратегий, из них Х открытых
- список открытых стратегий

**Comment by Rottenwood** [comment]
* страница редактирования профиля

**Comment by Rottenwood** [comment]
* возможность редактировать свои данные
